NVTLesson08CF/Models/NvtBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NVTLesson08CF.Models
{
    /// <summary>
    /// Tạo ra cấu trúc bảng
    /// </summary>
    public class NvtBook
    {
        [Key]
        public int NvtBookId { get; set; }
        public string NvtTitle { get; set; }
        public string NvtAuthor { get; set; }
        public int NvtYear { get; set; }
        public string NvtPublisher { get; set; }
        public string NvtPicture { get; set; }
        public int NvtCategoryId { get; set; }

        //Thuộc tính qhe
        public virtual NvtCategory GetNvtCategory  { get; set; }




    }
}

NVTLesson08CF/Models/NvtBookStore.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace NVTLesson08CF.Models
{
    public class NvtBookStore:DbContext
    {
        public NvtBookStore() : base("NvtBookStoreConnectionString")
        {

        }

        //Tạo các bảng
        public DbSet<NvtCategory> NvtCategories { get; set; }
        public DbSet<NvtBook> NvtBooks { get; set; }

    }
}

NVTLesson08CF/Models/NvtCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NVTLesson08CF.Models
{
    public class NvtCategory
    {
        [Key]
        public int NvtCategoryId { get; set; }
        public string CategoryName { get; set; }

        //Thuộc tính quan hệ
        public virtual ICollection<NvtBook> NvtBooks { get; set; }
    }
}

NVTLesson08CF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NVTLesson08CF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NvtAbout()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NVTLesson08CF/Controllers/NvtBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NVTLesson08CF.Models;

namespace NVTLesson08CF.Controllers
{
    public class NvtBooksController : Controller
    {
        private NvtBookStore db = new NvtBookStore();

        // GET: NvtBooks
        public ActionResult Index()
        {
            var nvtBooks = db.NvtBooks.Include(n => n.GetNvtCategory);
            return View(nvtBooks.ToList());
        }

        // GET: NvtBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NvtBook nvtBook = db.NvtBooks.Find(id);
            if (nvtBook == null)
            {
                return HttpNotFound();
            }
            return View(nvtBook);
        }

        // GET: NvtBooks/Create
        public ActionResult Create()
        {
            ViewBag.NvtCategoryId = new SelectList(db.NvtCategories, "NvtCategoryId", "CategoryName");
            return View();
        }

        // POST: NvtBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NvtBookId,NvtTitle,NvtAuthor,NvtYear,NvtPublisher,NvtPicture,NvtCategoryId")] NvtBook nvtBook)
        {
            if (ModelState.IsValid)
            {
                db.NvtBooks.Add(nvtBook);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.NvtCategoryId = new SelectList(db.NvtCategories, "NvtCategoryId", "CategoryName", nvtBook.NvtCategoryId);
            return View(nvtBook);
        }

        // GET: NvtBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NvtBook nvtBook = db.NvtBooks.Find(id);
            if (nvtBook == null)
            {
                return HttpNotFound();
            }
            ViewBag.NvtCategoryId = new SelectList(db.NvtCategories, "NvtCategoryId", "CategoryName", nvtBook.NvtCategoryId);
            return View(nvtBook);
        }

        // POST: NvtBooks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NvtBookId,NvtTitle,NvtAuthor,NvtYear,NvtPublisher,NvtPicture,NvtCategoryId")] NvtBook nvtBook)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nvtBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.NvtCategoryId = new SelectList(db.NvtCategories, "NvtCategoryId", "CategoryName", nvtBook.NvtCategoryId);
            return View(nvtBook);
        }

        // GET: NvtBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NvtBook nvtBook = db.NvtBooks.Find(id);
            if (nvtBook == null)
            {
                return HttpNotFound();
            }
            return View(nvtBook);
        }

        // POST: NvtBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NvtBook nvtBook = db.NvtBooks.Find(id);
            db.NvtBooks.Remove(nvtBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NVTLesson08CF/Controllers/NvtCategoryController.cs
using NVTLesson08CF.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NVTLesson08CF.Controllers
{
    public class NvtCategoryController : Controller
    {
        private static NvtBookStore _NvtBookStore;
        public NvtCategoryController()
        {
            _NvtBookStore = new NvtBookStore();
        }
        // GET: NvtCategory
        public ActionResult NvtIndex()
        {
            var nvtCategory = _NvtBookStore.NvtCategories.ToList();
            return View(nvtCategory);
        }
        [HttpGet]
        public ActionResult NvtCreate()
        {
            var nvtCategory = new NvtCategory();
            return View(nvtCategory);
        }
        [HttpPost]
        public ActionResult NvtCreate(NvtCategory nvtCategory)
        {
            _NvtBookStore.NvtCategories.Add(nvtCategory);
            _NvtBookStore.SaveChanges();
            return RedirectToAction("NvtIndex");
        }
    }
}

NVTLesson08CF/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NVTLesson08CF/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NVTLesson08CF/Views/Home/NvtAbout.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
<pre>
    Mã sinh viên:
    Họ tên: Nguyễn Văn Thạo
    Điện thoại:
    Email: 
    
</pre>

NVTLesson08CF/Views/NvtBooks/Create.cshtml
@model NVTLesson08CF.Models.NvtBook

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NvtBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NvtTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtPublisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtPublisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtPublisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtCategoryId, "NvtCategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NvtCategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NvtCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NVTLesson08CF/Views/NvtBooks/Delete.cshtml
@model NVTLesson08CF.Models.NvtBook

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NvtBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GetNvtCategory.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GetNvtCategory.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtAuthor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtPublisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtPublisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtPicture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NVTLesson08CF/Views/NvtBooks/Details.cshtml
@model NVTLesson08CF.Models.NvtBook

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NvtBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GetNvtCategory.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GetNvtCategory.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtAuthor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtAuthor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtPublisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtPublisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NvtPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NvtPicture)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NvtBookId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NVTLesson08CF/Views/NvtBooks/Edit.cshtml
@model NVTLesson08CF.Models.NvtBook

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NvtBook</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NvtBookId)

        <div class="form-group">
            @Html.LabelFor(model => model.NvtTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtAuthor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtAuthor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtAuthor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtPublisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtPublisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtPublisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NvtPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NvtPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NvtCategoryId, "NvtCategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NvtCategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NvtCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NVTLesson08CF/Views/NvtBooks/NvtIndex.cshtml
@model IEnumerable<NVTLesson08CF.Models.NvtBook>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GetNvtCategory.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtAuthor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtPublisher)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NvtPicture)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.GetNvtCategory.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtAuthor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtPublisher)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NvtPicture)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NvtBookId }) |
            @Html.ActionLink("Details", "Details", new { id=item.NvtBookId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NvtBookId })
        </td>
    </tr>
}

</table>

NVTLesson08CF/Views/NvtCategory/Index.cshtml
@model IEnumerable<NVTLesson08CF.Models.NvtCategory>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Nvt: Create New", "NvtCreate")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NvtCategoryId }) |
            @Html.ActionLink("Details", "Details", new { id=item.NvtCategoryId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NvtCategoryId })
        </td>
    </tr>
}

</table>

NVTLesson08CF/Views/NvtCategory/NvtCreate.cshtml
@model NVTLesson08CF.Models.NvtCategory

@{
    ViewBag.Title = "NvtCreate";
}

<h2>Nvt; NvtCreate</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="NVT: Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NVTLesson08CF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Nguyễn Văn Thạo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nguyễn Văn Thạo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Nvt: Ds Category", "NvtIndex", "NvtCategory")</li>
                    <li>@Html.ActionLink("Nvt: Ds Books", "NvtIndex", "NvtBooks")</li>


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>